### ISSUE TITLE
about run environment

### ISSUE THREAD

**Issue by enthusiasmYuan** [aliseyfi75/COSCI-GAN#1]
Hello, when I want to save the generated data, it shows that the module catch22 is not installed, but my installation process reports an error. I would like to ask what is your runtime environment? Thank you.

**Comment by aliseyfi75** [comment]
Hi
Could you please send the error message? Have you installed the catch22? You can install it using `pip install pycatch22`.

Also if you just want to generate the data and are not interested in extracting catch22 features for later analysis, you can remove all the part of the code that is related to catch22 package.

Let me know if you still have problem with the code by re-opening this issue.
