### ISSUE TITLE
Stock Data

### ISSUE THREAD

**Issue by patricklau12** [aliseyfi75/COSCI-GAN#3]
Hello, thanks for your work.

I followed the README to run the run.py and it generates five .pt files.
So, how can I create the synthetic data using them, and compare it with raw stock data using t-SNE and PCA?

Thanks.

**Comment by patricklau12** [comment]
How do you generate the generated_samples_LSTM_MLP_with_CD.csv

From Experiments/PCA_t-SNE/Stock_Dataset/Stock_visualization.ipynb
original_data = pd.read_csv('../../Dataset/stock_data_24.csv')
fake_data = pd.read_csv('Fake_Data/generated_samples_LSTM_MLP_with_CD.csv')

**Comment by aliseyfi75** [comment]
Hi!

Regarding your first question:

> Hello, thanks for your work.
> 
> I followed the README to run the run.py and it generates five .pt files. So, how can I create the synthetic data using them, and compare it with raw stock data using t-SNE and PCA?
> 
> Thanks.

You can use [generate_fake_data.ipynb](https://github.com/aliseyfi75/COSCI-GAN/blob/main/Experiments/All_Fake_Analysis/generate_fake_data.ipynb) to generate your synthetic data. I believe if you take a look at [Experiemnts](https://github.com/aliseyfi75/COSCI-GAN/tree/main/Experiments), it can be really helpful for you.

Regarding your second question:

> How do you generate the generated_samples_LSTM_MLP_with_CD.csv
> 
> From Experiments/PCA_t-SNE/Stock_Dataset/Stock_visualization.ipynb original_data = pd.read_csv('../../Dataset/stock_data_24.csv') fake_data = pd.read_csv('Fake_Data/generated_samples_LSTM_MLP_with_CD.csv')

The `generated_samples_LSTM_MLP_with_CD.csv` is the fake data generated via COSCI-GAN approach. Once you have your trained generators (Those .pt files you mentioned), you can go ahead and use them to generate your fake samples. You can take a look at [generate_fake_data.ipynb](https://github.com/aliseyfi75/COSCI-GAN/blob/main/Code/generate_fake_data.ipynb) to get a better understanding on how to do that.
