### ISSUE TITLE
Preprocess of stock_data_24

### ISSUE THREAD

**Issue by YuanXun2024** [aliseyfi75/COSCI-GAN#4]
Hi,

I find it difficult to understand the dataset stock_data_24. Can you please share the code of preprocessing stock_data or describe the logit of how you get stock_data_24 from stock_data? Thank you!

Xun

**Comment by aliseyfi75** [comment]
Hi Xun,

I used the `real_data_loading` function that Jinsung Yoon used in his paper, TimeGAN, to create that dataset. You can find the code here (https://github.com/jsyoon0823/TimeGAN/blob/master/data_loading.py#L80). What I did for creating the `stock_data_24` dataset was call that function, `real_data_loading('stock', 24)`. So 24 is essentially the length of each sequence we are trying to generate
