### ISSUE TITLE
How to calculate average euclidean distance (AED) for Freq changes and Anomalies datasets in Table 1

### ISSUE THREAD

**Issue by YuanXun2024** [aliseyfi75/COSCI-GAN#5]
Hi Ali,

In COSCI-GAN_demo.ipynb, you share the code for calculating AED for Simple Sine. But I am not sure how you calculate AED for Freq changes and Anomalies datasets in Table 1. Can you please share the relative code? Thank you.

Xun

**Comment by aliseyfi75** [comment]
Hi Xun,

You can find everything related to AED in the [Correlation_Analysis](https://github.com/aliseyfi75/COSCI-GAN/tree/main/Experiments/Correlation_Analysis) folder. More specifically, related to Freq changes and Anomalies dataset, you can take a look at [Time_Series_Analysis_freq_change.ipynb](https://github.com/aliseyfi75/COSCI-GAN/blob/main/Experiments/Correlation_Analysis/Toy_Datasets/Time_Series_Analysis_freq_change.ipynb) and [Time_Series_Analysis_anomaly.ipynb](https://github.com/aliseyfi75/COSCI-GAN/blob/main/Experiments/Correlation_Analysis/Toy_Datasets/Time_Series_Analysis_anomaly.ipynb).
